# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20160930_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
